name: Type Check

on:
  pull_request:
    branches: main
  push:
    branches:
      - main
jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install node v18
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: yarn install
        run: yarn install
      - name: tsc
        uses: icrawl/action-tsc@v1
